BEGIN;

ALTER TABLE public.users
    ADD COLUMN IF NOT EXISTS onboarding_complete boolean NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS public.missions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    title text NOT NULL,
    description text,
    status text NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'paused', 'completed', 'archived')),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS missions_user_status_idx
    ON public.missions (user_id, status);

CREATE TABLE IF NOT EXISTS public.commitments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    mission_id bigint NOT NULL REFERENCES public.missions(id) ON DELETE CASCADE,
    text text NOT NULL,
    deadline timestamp with time zone,
    status text NOT NULL DEFAULT 'pending'
        CHECK (status IN ('kept', 'missed', 'pending')),
    times_carried integer NOT NULL DEFAULT 0 CHECK (times_carried >= 0),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS commitments_user_status_deadline_idx
    ON public.commitments (user_id, status, deadline);
CREATE INDEX IF NOT EXISTS commitments_mission_idx
    ON public.commitments (mission_id);

CREATE TABLE IF NOT EXISTS public.outputs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    mission_id bigint NOT NULL REFERENCES public.missions(id) ON DELETE CASCADE,
    description text NOT NULL,
    logged_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS outputs_user_logged_at_idx
    ON public.outputs (user_id, logged_at DESC);
CREATE INDEX IF NOT EXISTS outputs_mission_idx
    ON public.outputs (mission_id);

CREATE TABLE IF NOT EXISTS public.coach_memory (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL UNIQUE REFERENCES public.users(id) ON DELETE CASCADE,
    pattern_label text,
    avoided_task text,
    days_active integer NOT NULL DEFAULT 0 CHECK (days_active >= 0),
    last_checkin_at timestamp with time zone,
    summary text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.coach_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    role text NOT NULL CHECK (role IN ('system', 'user', 'assistant', 'tool')),
    content text NOT NULL,
    session_date date NOT NULL DEFAULT CURRENT_DATE,
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS coach_messages_user_session_idx
    ON public.coach_messages (user_id, session_date, created_at);

-- These tables are accessed by the trusted backend connection. Enabling RLS
-- prevents accidental exposure through Supabase's public Data API until
-- explicit application policies are designed.
ALTER TABLE public.missions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.commitments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.outputs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coach_memory ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coach_messages ENABLE ROW LEVEL SECURITY;

COMMIT;
