BEGIN;

CREATE TABLE IF NOT EXISTS public.pattern_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    pattern_label text NOT NULL,
    reason text NOT NULL,
    evidence jsonb NOT NULL DEFAULT '[]'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS pattern_events_user_created_idx
    ON public.pattern_events (user_id, created_at DESC);

ALTER TABLE public.pattern_events ENABLE ROW LEVEL SECURITY;

COMMIT;
