CREATE TABLE IF NOT EXISTS push_subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  endpoint TEXT NOT NULL UNIQUE,
  subscription JSONB NOT NULL,
  timezone TEXT NOT NULL DEFAULT 'UTC',
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  last_sent_on DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_push_subscriptions_user_enabled
  ON push_subscriptions(user_id, enabled);

CREATE INDEX IF NOT EXISTS idx_push_subscriptions_send_window
  ON push_subscriptions(enabled, timezone, last_sent_on);

ALTER TABLE push_subscriptions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS push_subscriptions_backend_only ON push_subscriptions;
CREATE POLICY push_subscriptions_backend_only
  ON push_subscriptions
  FOR ALL
  USING (FALSE)
  WITH CHECK (FALSE);
